application: android-app-translation
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: src.main.application

- url: /translate
  script: src.main.application

- url: /css
  static_dir: static/css

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest